language:
- node_js
node_js:
- '5'
install:
- npm install
notifications:
  email: false
env:
- NODE_ENV=dev
deploy:
  provider: npm
  email: demircanomer91@gmail.com
  api_key:
    secure: ADnbrSv84Ku67arY/YUxfMruso7ky95mbcOqbV6wJoQUsuHPKWG023V30DOlSflcE8Nz5Et/+yp1ZI+ZLkbVAh6iB036CaP4Jo3dUXG86+9j48c0+zXde4NBWs2kZX8bO16FUU/Fuh01tjD4Fss4JaSCjd46ooZhRMH6EE43nprIUG9VKMgFPgF9XEU8q5kNi+plvS6HXQT1YFMcyIqi0DWtDiX35PNPEu0rcw5GVwFUrFlwD2VBVmx1kfbCow0wodUbkpqC7GEBj5Phd49L+Mt7ELC4mCDpR3vz4DKEynPmnyOovG0k8LNyC3OhI6cuYWTRv9PFF/utG0GDVw4kYTozGE1/Ra06hy4Umq8uoa6vXkBbP3ineKp0c9lbJDCuPf2AxDfZLCfvtN6SG+U50jshYocqvqBKdxiekQd/8NVtIZYeLOVyAurwHNdqoRG0IwCVOnyTeDE4VhbH+YvVGJLWTGk33ILmdDxnv5I7l/Y/qBujWDhQMwpb2b8xFvLNLMWEotPBbH8Ev0fnxbSICnZtHYZp/xblHP7tlV6YVqhWx12dfa3JuENhKUw/IcgIAbLlOHbBzeQ+DksuGHB/rj6NePcA3JpuAnGuSaKLY4Lj/7mGr5NyLsC7x0jftgu0b0icKrXmdpBffPVIEPJQNSto4zPeObDbRteVpUlRgc8=
  on:
    tags: true
    repo: omeroot/solwr
before_install:
- sudo apt-get install tar -y
before_script:
- npm install -g npm@'>=3.0.0'
- npm install -g mocha
- wget http://apache.mirror1.spango.com/lucene/solr/5.5.4/solr-5.5.4.tgz
- tar xzf solr-5.5.4.tgz solr-5.5.4/bin/install_solr_service.sh --strip-components=2
- sudo bash ./install_solr_service.sh solr-5.5.4.tgz
- sudo su - solr create_core -c '/opt/solr/bin/solr create_core -c querytest'
- sudo su - solr create_core -c '/opt/solr/bin/solr create_core -c products'
